/* This file was generated by Prostgles 
*/ 

 

import { ViewHandler, TableHandler, JoinMaker } from "prostgles-types";

export type TxCB = {
    (t: DBObj): (any | void | Promise<(any | void)>)
};


/* SCHEMA DEFINITON. Table names have been altered to work with Typescript */
export type Item_children = { 
  "id"?: number;
  "item_id"?: number;
  "name"?: string;
  "tst"?: Date;
}
export type Items = { 
  "id"?: number;
  "name"?: string;
  "tst"?: Date;
}
export type Tt = { 
  "t"?: string;
}
export type Various = { 
  "added"?: Date;
  "h"?: Array<string>;
  "id"?: number;
  "jsn"?: Object;
  "name"?: string;
  "tsv"?: any;
}

export type JoinMakerTables = {
 "item_children": JoinMaker<Item_children>;
 "items": JoinMaker<Items>;
};

/* DBO Definition. Isomorphic */
export type DBObj = {
  "item_children": TableHandler<Item_children> 
  "items": TableHandler<Items> 
  "tt": TableHandler<Tt> 
  "various": TableHandler<Various> 
  leftJoin: JoinMakerTables;
  innerJoin: JoinMakerTables;
  leftJoinOne: JoinMakerTables;
  innerJoinOne: JoinMakerTables;
};
