/* Schema definition generated by prostgles-server */

export type DBGeneratedSchema = {
  __rb_test_commit: {
    columns: {
      id?: null | number;
    };
    referencedBy: {};
  };
  "\"\"\"*\"\"\"": {
    columns: {
      "\"*\""?: null | string;
      id?: number;
      qq?: null | string;
    };
    referencedBy: {};
  };
  "\"\"\"quoted0\"\"\"": {
    columns: {
      "\"id0\""?: number;
      "\"quoted1_id\""?: null | number;
      "\"text_col0\""?: null | string;
    };
    referencedBy: {};
  };
  "\"\"\"quoted1\"\"\"": {
    columns: {
      "\"id1\""?: number;
      "\"quoted2_id\""?: null | number;
      "\"text_col1\""?: null | string;
    };
    referencedBy: {"\"\"\"quoted0\"\"\"":["\"quoted1_id\""]};
  };
  "\"\"\"quoted2\"\"\"": {
    columns: {
      "\"id2\""?: number;
      "\"text_col2\""?: null | string;
    };
    referencedBy: {"\"\"\"quoted1\"\"\"":["\"quoted2_id\""]};
  };
  "\"*\"": {
    columns: {
      "*"?: null | string;
      id?: number;
    };
    referencedBy: {};
  };
  api_table: {
    columns: {
      col1?: null | string;
      id?: number;
    };
    referencedBy: {};
  };
  ex_j_ins: {
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
    referencedBy: {};
  };
  files: {
    columns: {
      added?: string;
      cloud_url?: null | string;
      content_length?: number | string;
      content_type: string;
      deleted?: null | number | string;
      deleted_from_storage?: null | number | string;
      description?: null | string;
      etag?: null | string;
      extension: string;
      id?: string;
      name: string;
      original_name: string;
      signed_url?: null | string;
      signed_url_expires?: null | number | string;
      url: string;
    };
    referencedBy: {"users_public_info":["avatar"]};
  };
  geography_columns: {
    columns: {
      coord_dimension?: null | number;
      f_geography_column?: null | string;
      f_table_catalog?: null | string;
      f_table_name?: null | string;
      f_table_schema?: null | string;
      srid?: null | number;
      type?: null | string;
    };
    referencedBy: {};
  };
  geometry_columns: {
    columns: {
      coord_dimension?: null | number;
      f_geometry_column?: null | string;
      f_table_catalog?: null | string;
      f_table_name?: null | string;
      f_table_schema?: null | string;
      srid?: null | number;
      type?: null | string;
    };
    referencedBy: {};
  };
  insert_rules: {
    columns: {
      added?: null | string;
      id?: number;
      name?: null | string;
    };
    referencedBy: {};
  };
  items: {
    columns: {
      h?: null | string[];
      id?: number;
      name?: null | string;
    };
    referencedBy: {"items2":["items_id"],"items4a":["items_id"],"items_multi":["items0_id","items1_id","items2_id","items3_id"]};
  };
  items_multi: {
    columns: {
      id?: number;
      items0_id?: null | number;
      items1_id?: null | number;
      items2_id?: null | number;
      items3_id?: null | number;
      name?: null | string;
    };
    referencedBy: {};
  };
  items2: {
    columns: {
      hh?: null | string[];
      id?: number;
      items_id?: null | number;
      name?: null | string;
    };
    referencedBy: {"items4a":["items2_id"]};
  };
  items3: {
    columns: {
      h?: null | string[];
      id?: number;
      name?: null | string;
    };
    referencedBy: {};
  };
  items4: {
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
    referencedBy: {};
  };
  items4_pub: {
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
    referencedBy: {};
  };
  items4a: {
    columns: {
      id?: number;
      items_id?: null | number;
      items2_id?: null | number;
      name?: null | string;
    };
    referencedBy: {};
  };
  lookup_col1: {
    columns: {
      description?: null | string;
      id: "a" | "b"
    };
    referencedBy: {"uuid_text":["col1","col2","col3"]};
  };
  newly_created_table: {
    columns: {
      id?: null | number;
    };
    referencedBy: {};
  };
  obj_table: {
    columns: {
      id?: number;
      obj?: null | any;
    };
    referencedBy: {};
  };
  planes: {
    columns: {
      flight_number?: null | string;
      id?: number;
      last_updated: number | string;
      x?: null | number;
      y?: null | number;
    };
    referencedBy: {};
  };
  "prostgles_test.basic": {
    columns: {
      id?: number;
      txt?: null | string;
    };
    referencedBy: {"prostgles_test.basic1":["id_basic"]};
  };
  "prostgles_test.basic1": {
    columns: {
      id?: number;
      id_basic?: null | number;
      txt?: null | string;
    };
    referencedBy: {"prostgles_test.mv_basic1":["id"]};
  };
  "prostgles_test.mv_basic1": {
    columns: {
      id: number;
      id_basic: number;
      txt: string;
    };
    referencedBy: {};
  };
  rec: {
    columns: {
      id?: number;
      parent_id?: null | number;
      recf?: null | number;
    };
    referencedBy: {"rec":["parent_id"]};
  };
  rec_ref: {
    columns: {
      id?: number;
    };
    referencedBy: {"rec":["recf"]};
  };
  self_join: {
    columns: {
      id?: number;
      my_id?: null | number;
      my_id1?: null | number;
      name?: null | string;
    };
    referencedBy: {"self_join":["my_id","my_id1"]};
  };
  shapes: {
    columns: {
      geog?: null | string;
      geom?: null | string;
      id?: string;
    };
    referencedBy: {};
  };
  spatial_ref_sys: {
    columns: {
      auth_name?: null | string;
      auth_srid?: null | number;
      proj4text?: null | string;
      srid: number;
      srtext?: null | string;
    };
    referencedBy: {};
  };
  symbols: {
    columns: {
      id: string;
    };
    referencedBy: {"trades":["symbol"]};
  };
  table_name3434: {
    columns: {
      id: number;
    };
    referencedBy: {"table_name3434cccc":["id","id2"]};
  };
  table_name3434cccc: {
    columns: {
      id?: null | number;
      id2?: null | number;
    };
    referencedBy: {};
  };
  tjson: {
    columns: {
      colOneOf: "a" | "b" | "c"
      json: {    a: boolean;   arr: "1" | "2" | "3";   arr1: 1 | 2 | 3;   arr2: number[];   arrStr?: null | string[];   o?: | null
 |  {  o1: number; }
 |  {  o2: boolean; };  };
      jsonOneOf?: 
       | null
       |  {  command: "a"; }
       |  {  command: "b";  option: number[]; }
      status?: 
       | null
       |  {  ok: string; }
       |  {  err: string; }
       |  {  loading: {  loaded: number;  total: number; }; }
      table_config?: null | {    referencedTables?: (  {  name: string;  minFiles: number; } )[];   recType?: null | Record<"a" | "b",  {  bools: boolean[]; }>;  };
    };
    referencedBy: {};
  };
  tr1: {
    columns: {
      id?: number;
      t1?: null | string;
    };
    referencedBy: {"tr2":["tr1_id"]};
  };
  tr2: {
    columns: {
      id?: number;
      t1?: null | string;
      t2?: null | string;
      tr1_id?: null | number;
    };
    referencedBy: {"tr3":["tr2_id"]};
  };
  tr3: {
    columns: {
      id?: number;
      t2?: null | string;
      tr2_id?: null | number;
    };
    referencedBy: {};
  };
  trades: {
    columns: {
      id?: number;
      price: number | string;
      symbol: string;
    };
    referencedBy: {};
  };
  users: {
    columns: {
      email: string;
      id?: number;
      preferences: {    showIntro?: boolean;   theme?: "light" | "dark" | "auto";   others: any[];  };
      status: "active" | "disabled" | "pending"
    };
    referencedBy: {};
  };
  users_public_info: {
    columns: {
      avatar?: null | string;
      id?: number;
      name?: null | string;
      sid?: null | string;
    };
    referencedBy: {};
  };
  uuid_text: {
    columns: {
      col1?: null | "a" | "b"
      col2?: null | "a" | "b"
      col3?: null | "a" | "b"
      id?: null | string;
    };
    referencedBy: {};
  };
  v_items: {
    columns: {
      id?: null | number;
      name?: null | string;
    };
    referencedBy: {};
  };
  various: {
    columns: {
      added?: null | string;
      h?: null | string[];
      id?: number;
      jsn?: null | any;
      name?: null | string;
      tsv?: null | string;
    };
    referencedBy: {};
  };
  
}

/**
 * Data types as expected when selecting from the database
 * */
export type DBSchema = {
  [K in keyof DBGeneratedSchema]: Required<DBGeneratedSchema[K]["columns"]>;
};

/**
 * Data types as expected when inserting into the database (optional fields might be nullable/with defaults)
 * */
export type DBSchemaForInsert = {
  [K in keyof DBGeneratedSchema]: DBGeneratedSchema[K]["columns"];
};



export type GeneratedFunctionSchema = { 
  "myfunc": (args: {    arg1: number;  }) => Promise<number>;
  "myfuncVoid": () => Promise<void>;
  "myAdminFunc": (args: {    arg1: number;  }) => Promise<number>;
  "myfuncWithBadReturn": (args: {    arg1: number;  }) => Promise<string>;
  "myfuncWithComplexReturn": (args: {    arg1: number;  }) => Promise<(Array<number> | { a: number; b: string; c: { d: boolean } })>;
  "myfuncForDefault": () => Promise<void>;
  "myfuncForDefault2": (args: {    name: string;  }) => Promise<({ a: number; b?: undefined } | { b: string; a?: undefined })>;
}