-- DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE IF NOT EXISTS items (
	id	SERIAL PRIMARY KEY,
	name	TEXT
);

-- DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE IF NOT EXISTS items2 (
	id	SERIAL PRIMARY KEY,
	name	TEXT
);