/* This file was generated by Prostgles 
*/ 

 /* SCHEMA DEFINITON. Table names have been altered to work with Typescript */
/* DBO Definition */

export type DBSchemaGenerated = {
  "\"\"\"*\"\"\"": {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      "\"*\""?: null | string;
      id?: number;
      qq?: null | string;
    };
  };
  "\"*\"": {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      "*"?: null | string;
      id?: number;
    };
  };
  ex_j_ins: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
  };
  geography_columns: {
    is_view: true;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      coord_dimension?: null | number;
      f_geography_column?: null | string;
      f_table_catalog?: null | string;
      f_table_name?: null | string;
      f_table_schema?: null | string;
      srid?: null | number;
      type?: null | string;
    };
  };
  geometry_columns: {
    is_view: true;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      coord_dimension?: null | number;
      f_geometry_column?: null | string;
      f_table_catalog?: null | string;
      f_table_name?: null | string;
      f_table_schema?: null | string;
      srid?: null | number;
      type?: null | string;
    };
  };
  insert_rules: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      added?: null | string;
      id?: number;
      name?: null | string;
    };
  };
  items: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      h?: null | string[];
      id?: number;
      name?: null | string;
    };
  };
  items_m1: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      name: string;
    };
  };
  items_multi: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      items0_id?: null | number;
      items1_id?: null | number;
      items2_id?: null | number;
      items3_id?: null | number;
      name?: null | string;
    };
  };
  items_with_media: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      name?: null | string;
    };
  };
  items_with_one_media: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      items_m1_id?: null | number;
      name: string;
    };
  };
  items2: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      hh?: null | string[];
      id?: number;
      items_id?: null | number;
      name?: null | string;
    };
  };
  items3: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      h?: null | string[];
      id?: number;
      name?: null | string;
    };
  };
  items4: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
  };
  items4_pub: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      added?: null | string;
      id?: number;
      name: string;
      public?: null | string;
    };
  };
  items4a: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      items_id?: null | number;
      items2_id?: null | number;
      name?: null | string;
    };
  };
  lookup_col1: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id: string;
    };
  };
  obj_table: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      obj?: null | any;
    };
  };
  pg_attribute: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
    };
  };
  planes: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      flight_number?: null | string;
      id?: number;
      last_updated: number;
      x?: null | number;
      y?: null | number;
    };
  };
  prostgles_lookup_media_items_m1: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      foreign_id?: null | number;
      media_id: string;
    };
  };
  prostgles_lookup_media_various: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      foreign_id: number;
      media_id: string;
    };
  };
  rec: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      parent_id?: null | number;
      recf?: null | number;
    };
  };
  rec_ref: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
    };
  };
  shapes: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      geog?: null | string;
      geom?: null | string;
      id?: string;
    };
  };
  spatial_ref_sys: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      auth_name?: null | string;
      auth_srid?: null | number;
      proj4text?: null | string;
      srid: number;
      srtext?: null | string;
    };
  };
  tjson: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      colOneOf: string;
      json: any;
      jsonOneOf?: null | any;
      status?: null | any;
      table_config?: null | any;
    };
  };
  tr1: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      t1?: null | string;
    };
  };
  tr2: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: number;
      t1?: null | string;
      t2?: null | string;
      tr1_id?: null | number;
    };
  };
  users: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      email?: null | string;
      id?: number;
      preferences?: null | any;
      status?: null | string;
      type?: null | string;
    };
  };
  uuid_text: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      col1?: null | string;
      col2?: null | string;
      id?: null | string;
    };
  };
  v_items: {
    is_view: true;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      id?: null | number;
      name?: null | string;
    };
  };
  various: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      added?: null | string;
      h?: null | string[];
      id?: number;
      jsn?: null | any;
      name?: null | string;
      tsv?: null | string;
    };
  };
  various_nested: {
    is_view: false;
    select: true;
    insert: true;
    update: true;
    delete: true;
    columns: {
      name?: null | string;
      various_id?: null | number;
    };
  };
  
}
